controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_wheels:
      type: forward_command_controller/ForwardCommandController
    right_wheels:
      type: forward_command_controller/ForwardCommandController

left_wheels:
  ros__parameters:
    joints:
      - left_front_wheel_joint
      - left_rear_wheel_joint
    interface_name: velocity

right_wheels:
  ros__parameters:
    joints:
      - right_front_wheel_joint
      - right_rear_wheel_joint
    interface_name: velocity
